#############################################################################
# Makefile for building: VoqxQt3.app/Contents/MacOS/VoqxQt3
# Generated by qmake (2.01a) (Qt 4.8.7) on: qua mai 18 19:00:02 2016
# Project:  VoqxQt3.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile VoqxQt3.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.7_2/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/usr/local/Cellar/qt/4.8.7_2/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.7_2/lib -L/usr/local/Cellar/qt/4.8.7_2/lib -framework QtOpenGL -L/usr/local/opt/openssl/lib -L/usr/local/Cellar/qt/4.8.7_2/lib -F/usr/local/Cellar/qt/4.8.7_2/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Arquivo.cpp \
		Controlador.cpp \
		Modelo.cpp \
		Voxel.cpp \
		mainwindow.cpp \
		TelaModelo.cpp \
		Video.cpp \
		TelaVideo.cpp \
		CanvasModelo.cpp \
		CanvasVideo.cpp moc_mainwindow.cpp \
		moc_TelaModelo.cpp \
		moc_TelaVideo.cpp \
		moc_CanvasModelo.cpp \
		moc_CanvasVideo.cpp
OBJECTS       = main.o \
		Arquivo.o \
		Controlador.o \
		Modelo.o \
		Voxel.o \
		mainwindow.o \
		TelaModelo.o \
		Video.o \
		TelaVideo.o \
		CanvasModelo.o \
		CanvasVideo.o \
		moc_mainwindow.o \
		moc_TelaModelo.o \
		moc_TelaVideo.o \
		moc_CanvasModelo.o \
		moc_CanvasVideo.o
DIST          = /usr/local/Cellar/qt/4.8.7_2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/include_source_dir.prf \
		VoqxQt3.pro
QMAKE_TARGET  = VoqxQt3
DESTDIR       = 
TARGET        = VoqxQt3.app/Contents/MacOS/VoqxQt3

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile VoqxQt3.app/Contents/PkgInfo VoqxQt3.app/Contents/Resources/empty.lproj VoqxQt3.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_TelaVideo.h ui_TelaModelo.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) VoqxQt3.app/Contents/MacOS/ || $(MKDIR) VoqxQt3.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VoqxQt3.pro  /usr/local/Cellar/qt/4.8.7_2/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.7_2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.7_2/lib/QtOpenGL.framework/QtOpenGL.prl \
		/usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile VoqxQt3.pro
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.7_2/lib/QtOpenGL.framework/QtOpenGL.prl:
/usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile VoqxQt3.pro

VoqxQt3.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) VoqxQt3.app/Contents || $(MKDIR) VoqxQt3.app/Contents 
	@$(DEL_FILE) VoqxQt3.app/Contents/PkgInfo
	@echo "APPL????" >VoqxQt3.app/Contents/PkgInfo
VoqxQt3.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) VoqxQt3.app/Contents/Resources || $(MKDIR) VoqxQt3.app/Contents/Resources 
	@touch VoqxQt3.app/Contents/Resources/empty.lproj
	
VoqxQt3.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) VoqxQt3.app/Contents || $(MKDIR) VoqxQt3.app/Contents 
	@$(DEL_FILE) VoqxQt3.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,VoqxQt3,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.7_2/mkspecs/unsupported/macx-clang-libc++/Info.plist.app >VoqxQt3.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/VoqxQt31.0.0 || $(MKDIR) .tmp/VoqxQt31.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/VoqxQt31.0.0/ && $(COPY_FILE) --parents Arquivo.h Controlador.h Modelo.h Voxel.h mainwindow.h TelaModelo.h Video.h TelaVideo.h CanvasModelo.h CanvasVideo.h .tmp/VoqxQt31.0.0/ && $(COPY_FILE) --parents main.cpp Arquivo.cpp Controlador.cpp Modelo.cpp Voxel.cpp mainwindow.cpp TelaModelo.cpp Video.cpp TelaVideo.cpp CanvasModelo.cpp CanvasVideo.cpp .tmp/VoqxQt31.0.0/ && $(COPY_FILE) --parents mainwindow.ui TelaVideo.ui TelaModelo.ui .tmp/VoqxQt31.0.0/ && (cd `dirname .tmp/VoqxQt31.0.0` && $(TAR) VoqxQt31.0.0.tar VoqxQt31.0.0 && $(COMPRESS) VoqxQt31.0.0.tar) && $(MOVE) `dirname .tmp/VoqxQt31.0.0`/VoqxQt31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/VoqxQt31.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r VoqxQt3.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_TelaModelo.cpp moc_TelaVideo.cpp moc_CanvasModelo.cpp moc_CanvasVideo.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_TelaModelo.cpp moc_TelaVideo.cpp moc_CanvasModelo.cpp moc_CanvasVideo.cpp
moc_mainwindow.cpp: ui_mainwindow.h \
		TelaModelo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h \
		TelaVideo.h \
		mainwindow.h
	/usr/local/Cellar/qt/4.8.7_2/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_TelaModelo.cpp: Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h \
		TelaModelo.h
	/usr/local/Cellar/qt/4.8.7_2/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ TelaModelo.h -o moc_TelaModelo.cpp

moc_TelaVideo.cpp: Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h \
		TelaVideo.h
	/usr/local/Cellar/qt/4.8.7_2/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ TelaVideo.h -o moc_TelaVideo.cpp

moc_CanvasModelo.cpp: Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h \
		CanvasModelo.h
	/usr/local/Cellar/qt/4.8.7_2/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ CanvasModelo.h -o moc_CanvasModelo.cpp

moc_CanvasVideo.cpp: Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h \
		CanvasVideo.h
	/usr/local/Cellar/qt/4.8.7_2/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ CanvasVideo.h -o moc_CanvasVideo.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_TelaVideo.h ui_TelaModelo.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_TelaVideo.h ui_TelaModelo.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Cellar/qt/4.8.7_2/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_TelaVideo.h: TelaVideo.ui \
		CanvasVideo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h
	/usr/local/Cellar/qt/4.8.7_2/bin/uic TelaVideo.ui -o ui_TelaVideo.h

ui_TelaModelo.h: TelaModelo.ui \
		CanvasModelo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h
	/usr/local/Cellar/qt/4.8.7_2/bin/uic TelaModelo.ui -o ui_TelaModelo.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		ui_mainwindow.h \
		TelaModelo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h \
		TelaVideo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Arquivo.o: Arquivo.cpp Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Arquivo.o Arquivo.cpp

Controlador.o: Controlador.cpp Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controlador.o Controlador.cpp

Modelo.o: Modelo.cpp Modelo.h \
		Voxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Modelo.o Modelo.cpp

Voxel.o: Voxel.cpp Voxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Voxel.o Voxel.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		TelaModelo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h \
		TelaVideo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

TelaModelo.o: TelaModelo.cpp TelaModelo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TelaModelo.o TelaModelo.cpp

Video.o: Video.cpp Video.h \
		Voxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Video.o Video.cpp

TelaVideo.o: TelaVideo.cpp TelaVideo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TelaVideo.o TelaVideo.cpp

CanvasModelo.o: CanvasModelo.cpp CanvasModelo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CanvasModelo.o CanvasModelo.cpp

CanvasVideo.o: CanvasVideo.cpp CanvasVideo.h \
		Controlador.h \
		Arquivo.h \
		Modelo.h \
		Voxel.h \
		Video.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CanvasVideo.o CanvasVideo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_TelaModelo.o: moc_TelaModelo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TelaModelo.o moc_TelaModelo.cpp

moc_TelaVideo.o: moc_TelaVideo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TelaVideo.o moc_TelaVideo.cpp

moc_CanvasModelo.o: moc_CanvasModelo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CanvasModelo.o moc_CanvasModelo.cpp

moc_CanvasVideo.o: moc_CanvasVideo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CanvasVideo.o moc_CanvasVideo.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

